[build]
  command = "bash ./netlify-build.sh"
  publish = "build/web"

[build.environment]
  # Flutter settings
  FLUTTER_VERSION = "stable"
  FLUTTER_CHANNEL = "stable"
  
  # Build settings
  NODE_VERSION = "18"
  
  # Clean build identifier
  CACHE_BUSTER = "fresh-html-build-20250824"

# Build processing
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# SPA routing for Flutter web
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers optimized for Flutter web HTML renderer
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=(), usb=()"
    # Clean CSP for HTML renderer with Google Fonts support
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' data: https://fonts.gstatic.com https://fonts.googleapis.com; img-src 'self' data: https: blob:; connect-src 'self' https://zifbuzsdhparxlhsifdi.supabase.co wss://realtime.supabase.co https://api.openweathermap.org wss://*.supabase.co; object-src 'none'; worker-src 'self' blob:; child-src 'self' blob:; frame-src 'none'; media-src 'self' blob: data:;"

# Cache optimization for Flutter web HTML renderer
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Flutter-specific files
[[headers]]
  for = "/flutter.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/flutter_bootstrap.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Content-Type = "application/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/main.dart.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "application/javascript; charset=utf-8"

# No cache for main HTML file
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Manifest and favicon
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "application/json"

[[headers]]
  for = "/favicon.png"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Service worker
[[headers]]
  for = "/flutter_service_worker.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Content-Type = "application/javascript"

# Build info
[[headers]]
  for = "/build-info.txt"
  [headers.values]
    Cache-Control = "no-cache"
    Content-Type = "text/plain"