[build]
  command = "npm install && ./build_for_netlify.sh"
  publish = "build/web"
  functions = "netlify/functions"

 [build.processing]
  skip_processing = true
  
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
