[build]
command = "./netlify-build.sh"
publish = "build/web"

[build.environment]
FLUTTER_VERSION = "3.27.1"
NODE_VERSION = "18"

# Disable all processing to avoid compression issues
[build.processing]
skip_processing = true

[context.production.environment]
FLUTTER_ENVIRONMENT = "production"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
# Temporarily disable CSP to troubleshoot ERR_CONTENT_DECODING_FAILED
# Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; font-src 'self' data:; img-src 'self' data: blob:; connect-src 'self' https://zifbuzsdhparxlhsifdi.supabase.co https://showtrackai.app.n8n.cloud; worker-src 'none'; object-src 'none';"

[[headers]]
for = "/*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
Content-Type = "application/javascript; charset=utf-8"
# Prevent double compression
Content-Encoding = ""

# Special handling for Flutter bootstrap file to prevent encoding issues
[[headers]]
for = "/flutter_bootstrap.js"
[headers.values]
Cache-Control = "no-cache"
Content-Type = "application/javascript; charset=utf-8"
Content-Encoding = ""

# Special handling for main dart file
[[headers]]
for = "/main.dart.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
Content-Type = "application/javascript; charset=utf-8"
Content-Encoding = ""

[[headers]]
for = "/*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.woff2"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# CanvasKit files
[[headers]]
for = "/canvaskit/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# WASM files need special handling
[[headers]]
for = "/*.wasm"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
Content-Type = "application/wasm"

[[headers]]
for = "/flutter_service_worker.js"
[headers.values]
Cache-Control = "no-cache"
Content-Type = "application/javascript; charset=utf-8"
Content-Encoding = ""

[[headers]]
for = "/index.html"
[headers.values]
Cache-Control = "no-cache"

[[headers]]
for = "/version.json"
[headers.values]
Cache-Control = "no-cache"

# Disable compression for specific file types that cause ERR_CONTENT_DECODING_FAILED
[[headers]]
for = "*.dart.js"
[headers.values]
Content-Type = "application/javascript; charset=utf-8"
Content-Encoding = ""
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.js.map"
[headers.values]
Content-Type = "application/json"
Content-Encoding = ""

[[redirects]]
from = "/*"
to = "/index.html"
status = 200