[build]
  command = "bash ./netlify-build.sh"
  publish = "build/web"
  functions = "netlify/functions"

[build.environment]
  # Flutter settings for 3.32+
  FLUTTER_VERSION = "stable"
  FLUTTER_CHANNEL = "stable"
  
  # Build settings
  NODE_VERSION = "18"
  
  # Performance optimizations
  DART_DEFINES_CACHE = "true"
  FLUTTER_BUILD_VERBOSE = "false"
  
  # Cache buster for forcing rebuilds
  CACHE_BUSTER = "v6-20250824-import-fix"

# Build command timeout (30 minutes)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# SPA routing for Flutter web
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle Flutter routing
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Security headers optimized for Flutter web
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Updated permissions policy - no geolocation needed
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=(), usb=()"
    # Content Security Policy for Flutter web HTML renderer - no external font/canvas dependencies
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; font-src 'self' data:; img-src 'self' data: https: blob:; connect-src 'self' https://zifbuzsdhparxlhsifdi.supabase.co wss://realtime.supabase.co https://api.openweathermap.org wss://*.supabase.co; object-src 'none'; worker-src 'self' blob:; child-src 'self' blob:; frame-src 'none'; media-src 'self' blob: data:;"

# Optimize caching for Flutter web assets (HTML renderer only)
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Flutter-specific headers
[[headers]]
  for = "/flutter.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/flutter_bootstrap.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/main.dart.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# CORS for serverless functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS, PATCH"

# Prevent caching of the main HTML file
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Handle manifest and favicon
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "application/json"

[[headers]]
  for = "/favicon.png"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Flutter service worker
[[headers]]
  for = "/flutter_service_worker.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Content-Type = "application/javascript"

# Build status endpoint
[[headers]]
  for = "/build-info.txt"
  [headers.values]
    Cache-Control = "no-cache"
    Content-Type = "text/plain"
