name: showtrackai_journaling
description: ShowTrackAI Agricultural Education Platform with Journaling Integration

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies for existing app
  cupertino_icons: ^1.0.8
  
  # Database and backend
  supabase_flutter: ^2.8.6
  http: ^1.2.2
  
  # State management and utilities
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  
  # UI components
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  
  # JSON handling
  json_annotation: ^4.9.0
  
  # Development utilities
  uuid: ^4.5.1
  
  # Geolocation packages - Updated for compatibility
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  permission_handler: ^11.3.1
  
  # Weather API (optional - can use existing http package)
  weather: ^3.1.1
  
  # Maps (optional - for future enhancements) - Updated for compatibility
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  
  # Assets for the app
  assets:
    - assets/images/
    - assets/icons/

# Override dependency resolution issues
dependency_overrides:
  # Resolve version conflicts
  leak_tracker: ^11.0.0
  leak_tracker_flutter_testing: ^3.0.5
  leak_tracker_testing: ^3.0.1
  vm_service: ^15.0.2