name: showtrackai_journaling
description: ShowTrackAI Agricultural Education Platform with Journaling Integration

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies for existing app
  cupertino_icons: ^1.0.6
  
  # Database and backend
  supabase_flutter: ^2.0.0
  http: ^1.2.1
  
  # State management and utilities
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  
  # UI components - removed google_fonts to avoid external dependencies
  flutter_svg: ^2.0.9
  
  # JSON handling
  json_annotation: ^4.8.1
  
  # Development utilities
  uuid: ^4.2.1
  intl: ^0.19.0
  
  # Web support for file download (using web-safe alternative)
  # universal_html: ^2.2.4 # Commented out - not WebAssembly compatible
  
  # Geolocation - use web-safe alternative or conditional import
  geolocator: ^10.1.0
  geolocator_web: ^2.2.1  # Explicit web implementation
  permission_handler: ^11.1.0
  
  # Weather API (using http package instead of weather package)

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  # Assets for the app
  assets:
    - assets/images/
    - assets/icons/